중간점검차원에서 PR보냅니다.
SLCube/shop pull request #17
Opened 2023-01-31 12:03 UTC by SLCube

일단 Spring Security를 처음부터 설정하는건 굉장히 오랜만이라 어려우면서도 재밌게 했던것 같습니다.

참고한 자료는 인프런의 정수원님 강의중 Ajax인증 구현부분을 참고했습니다. 이유는 rest api서버를 만드는것이 목표인 상황에서 강의내용안에 제가 필요한 내용이 많다 느꼈기 때문입니다.

예외메세지 처리가 부족한게 느껴집니다. 좋은 가이드라인을 알려주시면 감사하겠습니다.

MemberService의 메소드중 login메소드는 이제 필요없어질거 같습니다. 삭제를 해도 될거같은데 제가 생각하는것이 맞나요?

추가로 Spring Security설정 내용중 보완해야될 부분을 짚어주시면 감사하겠습니다.

2023-01-31 13:16 UTC, kihwankim requested changes
Redis가 loacl환경이 없어 보이는데 혹시 local환경에서 어떻게 뜨는지 알 수 있을까요??
혹시 없을 경우 in memory 방식의 redis를 사용하는 것을 추천드립니다!

2023-01-31 13:16 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/repository/MemberRepositoryHelper.java
>      }
이건 의미가 없어 보이는데 삭제해도 괜찮을꺼 같아요!

2023-01-31 13:33 UTC, SLCube commented on src/main/java/com/slcube/shop/business/member/repository/MemberRepositoryHelper.java
>      }
해당메소드는 src/main/java/com/slcube/shop/common/security/service/CustomUserDetailsService.java에서 사용중입니다. 
제가 질문드린 메소드는 src/main/java/com/slcube/shop/business/member/service/MemberServiceImpl.java인데 다시한번 확인 부탁드려도 될까요?

2023-01-31 13:38 UTC, SLCube commented
현재 제 local환경에 redis를 설치해 실행시키는 상황입니다. in memory방식의 redis라면 embedded형식의 redis를 말씀하시는건가요?

2023-01-31 14:00 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/repository/MemberRepositoryHelper.java
>      }
MemberServiceImpl은 현재 코드에 없어서 리뷰가 힘들거같아요 기존에 변경되지 않은 코드는 리뷰를 할 수 없으니 이부분 이해해주세요....

2023-01-31 14:01 UTC, kihwankim requested changes
네네 redis embedded redis 이용해서 local 환경 설정 부탁드려요 git repo 다운받고 바로 test code 실행이 가능해야하지만 현재는 불가능해보여서요

2023-01-31 14:10 UTC, SLCube commented on src/main/java/com/slcube/shop/business/member/repository/MemberRepositoryHelper.java
>      }
import구문은 생략했습니다.
```
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class MemberServiceImpl implements MemberService {

    private final MemberRepository memberRepository;
    private final MemberRepositoryHelper memberRepositoryHelper;
    private final PasswordEncoder passwordEncoder;

    @Override
    @Transactional
    public Long signUp(MemberSignUpRequestDto requestDto) {
        String password = requestDto.getPassword();
        requestDto.setPassword(passwordEncoder.encode(password));

        Member member = MemberMapper.toEntity(requestDto);
        return memberRepository.save(member).getId();
    }

    @Override
    public MemberResponseDto login(MemberLoginDto requestDto) {
        String email = requestDto.getEmail();
        String password = requestDto.getPassword();
        Member member = memberRepositoryHelper.findByEmailAndMemberStatus(memberRepository, email, MemberStatus.MEMBER);

        if (!passwordEncoder.matches(password, member.getPassword())) {
            throw new IllegalArgumentException("아이디 혹은 비밀번호를 확인해주세요.");
        }

        return new MemberResponseDto(member);
    }

    @Override
    @Transactional
    public Long changePassword(MemberChangePasswordRequestDto requestDto) {
        String email = requestDto.getEmail();
        Member member = memberRepositoryHelper.findByEmailAndMemberStatus(memberRepository, email, MemberStatus.MEMBER);

        String changedPassword = requestDto.getChangedPassword();
        member.changePassword(passwordEncoder.encode(changedPassword));

        return member.getId();
    }
}
```

2023-01-31 14:48 UTC, SLCube commented
네 알겠습니다. 다운받고 바로 test code 실행이 가능하게끔 추가로 in-memory h2 db 설정도 추가하겠습니다.

2023-02-01 12:48 UTC, kihwankim requested changes
test 환경에서 port 사용 유무 확인 해주는 기능이 필요해 보입니다!
그리고 위에 언급한 것과 같이 service 분리 및 병합은 고민 해보고 한번 시도해봐주세요!

2023-02-01 12:48 UTC, kihwankim commented on src/main/java/com/slcube/shop/common/exception/CustomErrorCode.java
>      INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "서버 에러입니다.");
message를 좀더 자세하게 하고싶을 경우는 ... 음 ...저는 솔직히 enum을 더 세분화 해서 쓰던제 아니면 logging을 해서 세분화해서 에러 메시지를 저장하고 있어요

2023-02-01 12:48 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/repository/MemberRepositoryHelper.java
>      }
저생각에는 `CustomUserDetailsService` 를 만들지 않고 `MemberServiceImpl`에 `UserDetailsService` 를 상속 시킬 거같은데... 이미 나눈거 그러면 `MemberServiceImpl` 에서는 login 기능만 제거하고, `CustomUserDetailsService` class 이름은 는 너무 추상적인거같아 AuthenticateionService 가 좋을듯합니다.

그러면 `AuthenticateionService`는 로그인 기능만 담당하고, `MemberServiceImpl` 는 회원 관리 측면만 담당하는게 좋을듯합니다. 아니면 위에 처럼 하나로 합쳐서 member service 로 설정하든지요

2023-02-01 12:48 UTC, kihwankim commented on src/main/java/com/slcube/shop/common/config/redis/EmbeddedRedisConfig.java
> +    }
해당 port를 이미 사용할 경우 에러가 날거 같아요 이경우도 고려해서 작성하면 좋을거 같아요
windows mac OS에 명령어로 port 사용유무 확인 해서 connection을 맺어 주면 좋을듯합니다

2023-02-02 12:18 UTC, SLCube commented on src/main/java/com/slcube/shop/common/exception/CustomErrorCode.java
>      INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "서버 에러입니다.");
그러면 일단은 현재 상태를 유지하고 메세지의 개수가 많아지면 말씀하신 방법중 선택하는 방향으로 하겠습니다.

2023-02-02 12:25 UTC, SLCube commented on src/main/java/com/slcube/shop/business/member/repository/MemberRepositoryHelper.java
>      }
MemberServiceImpl에 UserDetailsService를 상속시키는 방법으로 진행하겠습니다. 감사합니다.

2023-02-02 12:32 UTC, kihwankim approved these changes
고생하셨습니다~!

2023-02-02 12:39 UTC, merged