장바구니 service 구현
SLCube/shop pull request #20
Opened 2023-02-04 11:35 UTC by SLCube

이전에 Entity를 설계할때 cart와 item사이에 relation entity를 만들었지만 필요가 없을거같아 제거후 item, cart, member entity간 연관관계를 재정의 해줬습니다.

추가로 구현과정이 전체적으로 반복되는거 같습니다. 정상적인 현상인지 의견을 나눴으면 합니다.

2023-02-04 13:01 UTC, kihwankim requested changes
validation 로직 추가와 oom 이 발생할 수 있는 로직이 있어서 요케이스는 한번 고민해주세요!

2023-02-04 13:01 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/cart/domain/Cart.java
> +    }
여기에 quantity 가 1이 이상일때만 입력 가능하게 해주면 좋을거같아요 혹시 validation 로직이 외부에 있나요??
없으면 validation bean class를 만들고 거기에 validation 로직을 넣어주면 좋을듯합니다!
저는 entity 내부에 validation 로직을 넣는것보다는 validation로직만 있는 bean class를 따로 빼서 작업을 하고있습니다
스타일  차이이므로 한번 검토해서 해보시길 바랍니다!

2023-02-04 13:01 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/cart/domain/Cart.java
> +    private int quantity = 1;
여기에 1을 defulat 값으로 넣었는데 이건 생성자에 넣어주는게 어떨까요??

2023-02-04 13:01 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
> +    private List<Cart> carts = new ArrayList<>();
Cart 개수가 많아지면 pagination으로 작업할거 같아요 Member 에 one to many 는 좀 안좋은 선택일 수 있다고 생각이 드네요

2023-02-04 13:01 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
>      private List<Order> orders = new ArrayList<>();
요건 저도 못봤었는데 주문을 3년동안 1000만건 하는 사람도 존재하 수 있는데 요케이스에서는 OOM(Out Of Memory)를 유발 할 수 있을듯합니다! 요것도 고려 부탁드려요

추가로 order에서 member를 fetch join 하는 경우는 많을 것 이지만 member가 order를 조회 하는 경우는 거의 없을 듯합니다!

2023-02-04 13:41 UTC, kihwankim requested changes
Member Entity 내부에 OOM 이 될 수 있는 것들이 많네요 하나 하나 찾아주는것 보다는 한번 고민해서 제거 한번 해보시면 좋을듯해요!

2023-02-04 13:41 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/cart/domain/Cart.java
> +        return cart;
이것도 그냥 생성자로 한번에 만들어지게 하는게 어떨까요?? 스타일 차이긴한데 .... 일단 저의 생각입니다

2023-02-04 13:41 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/cart/repository/CartQueryRepository.java
> +    public List<Cart> findAllCarts(Pageable pageable);
요건 querydsl 말고 바로 data jpa 써도 괜찮지 않을까요??
Slice랑 page 데이터 없이 사용하는 이유가 따로있나요??

2023-02-04 13:41 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/cart/repository/CartRepositoryHelper.java
> +                .orElseThrow(() -> new CartItemNotFoundException());
method이름이랑 내부 구현이랑 매칭이 안되어 보이는데 실수로 하신건가요??
deleted 가 아닌 값을 불러오는게 아니라 deleted인 값을 불러 오는 건가요??

2023-02-04 13:41 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
내가쓴 리뷰가 1000만개면 OOM 날거 같아요 그리고 바운디드 컨텍스트 기준으로 나누는 것라고 해서 domain을 나누는 기준을 세우는게 있어요 혹시 이부분 한번 학습해보시는게 어떨까요??
나중에 domain 별로 잘 나뉘어져 있다면 서버 분리 및 사이클 관리에 좋아서 한번 추천드려요! 한번 학습해보시고 부족하거나 설명 필요한건 요청주세요

2023-02-04 13:52 UTC, SLCube commented on src/main/java/com/slcube/shop/business/cart/repository/CartRepositoryHelper.java
> +                .orElseThrow(() -> new CartItemNotFoundException());
실수입니다. 수정하겠습니다.

2023-02-04 13:59 UTC, SLCube commented on src/main/java/com/slcube/shop/business/cart/repository/CartQueryRepository.java
> +    public List<Cart> findAllCarts(Pageable pageable);
그렇네요 querydsl을 사용할 이유가 없어보입니다.

2023-02-05 10:18 UTC, kihwankim approved these changes
Page interface에서 map method 한번 확인해 보면 좋을듯합니다!
map method 사용 여부는 고민해보시고 하고 싶으면 하고 아니면 적용은 안해도 될거같네요!
편하게 선택해서 진행해 주세요!
고생 많으셨습니다!

2023-02-05 10:18 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/cart/service/CartServiceImpl.java
> +        return new PageImpl<>(result, pageable, totalElements);
Page interface에서는 map이라는 함수가 존재해요 해당 함수를 이용하면 PageImpl 객체를 다시 안 만들어도 되니까 편리해 보이네요! 필요하면 사용해 보시는걸 추천 드립니다

2023-02-05 10:20 UTC, SLCube commented on src/main/java/com/slcube/shop/business/cart/service/CartServiceImpl.java
> +        return new PageImpl<>(result, pageable, totalElements);
네 확인해보고 필요하면 적용해보겠습니다.

2023-02-05 11:19 UTC, merged