Feature/#23  Member, Cart, Item Controller 구현 및 Service 수정
SLCube/shop pull request #25
Opened 2023-02-15 12:42 UTC by SLCube

구현중 하나의 브랜치 안에서 너무 많은 작업이 이루어지는것 같아 지난번에 이슈를 남겼습니다.([issue#24](https://github.com/SLCube/shop/issues/24))

이미 작업된 내용들이 있어 이번 PR에 여러 작업이 포함된점 양해 부탁드리겠습니다.

[CartControllerTest.java](https://github.com/SLCube/shop/blob/feature/%2323/src/test/java/com/slcube/shop/business/cart/controller/CartControllerTest.java#L54-L71)에서 CartService를 mocking하고 [saveCart](https://github.com/SLCube/shop/blob/feature/%2323/src/main/java/com/slcube/shop/business/cart/service/CartServiceImpl.java#L30-L40) 메소드의 행동을 정의했는데, 콘솔에 출력할땐 정의한 행동대로 출력이 되지만, mockMvc로 테스트할땐 0으로 출력되는 현상이 있었습니다. 해당 문제에 대해 알고계신것이 있다면 공유 부탁드리겠습니다.

추가로 문제가 될만한 코드나, 수정해야될 코드가 있다면 그에 대해서도 리뷰 부탁드리겠습니다.

감사합니다.

2023-02-16 13:39 UTC, kihwankim commented
답글 먼저 드리자면 given when then 에서 입력값이랑 동일한건 hashCode() 까지 동일해야하지만 현재 hashCode 재정의도 하지 않고 새로운 객체를 만들어서 같은 객체라고 인식 못하는거 같아서 저 생각에는 `any(Member~~.class)` 로 하는게 좋을거같아요 mocking할때 특수 값을 파라미터로 잘 안넘기고 `anyLong()`, `anyString()` 과 같이 처리하는게 더 유지 보수성이 좋습니다

2023-02-16 13:53 UTC, kihwankim requested changes
리뷰 요청서에서는 test code 가 통과 하지 못한걸로 보여져서 일단 변경 요청을 드릴게요 저가 남긴 내용 바탕으로 한번 더 고민해 보시고 아니면 기존방식 유지하셔도 됩니다

2023-02-16 13:53 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
> +public class Member extends BaseTimeEntity implements Serializable {
`Serialzable` 를 붙인 이유가 있을까요??

2023-02-16 13:53 UTC, kihwankim commented on src/main/java/com/slcube/shop/common/config/jpa/LoginUserAuditorAware.java
> +        }
요건 무조건 not null인걸로 보여지는데 그냥 Optional없이 쓰는게 어떨까요?? 새로운 개발자가 보면 null 가능성 때문에 null check도 필요해 보여서 코드 가독성에 해칠거같아서요
```suggestion
        if (authentication.getPrincipal().equals(ANONYMOUS_USER.getMemberStatus())) {
            return ANONYMOUS_USER.getMemberStatus();
        }
```

만약 다른 곳에서 Opional을 반환 해야하면 그때는 `Optional.of()` method를 추천 드립니다

2023-02-16 13:53 UTC, kihwankim commented on src/test/java/com/slcube/shop/business/cart/controller/CartControllerTest.java
> +
```suggestion

        given(cartService.saveCart(any(CartSaveRequestDto.class), any(memberContext.class)))
                .willReturn(1L);

```
테스트 코드 또한 관리 포인트 중에 하나입니다 그리고 테스트 코드 관리에서 특정 파라미터를 지정하면 나중에 파라미터 하나하나 다 관리해야해서 어려움이 있을 수 있습니다
그러므로 저는 any 를 넣어서 아무 값이나 들어와도 저렇게 반환 될 수 있도록 하는걸 추천해요 만약 a 값을 입력하면 A가 나오고 b값을 입력하면 B가 나올 경우에만 저는 특정 값을 넣어 주는 형태로 개발을 합니다

2023-02-18 11:44 UTC, SLCube commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
> +public class Member extends BaseTimeEntity implements Serializable {
Serializable을 안붙였을때 로그인 시도를 하면 org.springframework.data.redis.serializer.SerializationException 예외가 발생했습니다. 간단히 생각한 해결방법은 Serializable을 붙여서 직렬화 대상으로 선언했고, 해결되는듯 했습니다.

그런데 실제 redis에 저장되는 데이터를 살펴보니 \x00 \x00... 이런식으로 알아보기 힘든 형태로 저장됐고, 현재 해당 이슈에 대해 해결중에 있습니다.

2023-02-20 12:18 UTC, kihwankim approved these changes

2023-02-20 12:18 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/address/dto/AddressUpdateRequestDto.java
>      private boolean isDefaultAddress;
이러면 null 이면 바로 false가 default로 될거 같아요 boolean 에서 Boolean으로 변경하는게 어떨까요??

2023-02-20 12:18 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
> +public class Member extends BaseTimeEntity implements Serializable {
@SLCube entity 를 redis에 그대로 저장하는건 위험할거같아요 혹시 redis저장용 dto class 파는게 어떨까요??
entity class 는 회원 요구사항이 변경될때마다 변경이 이뤄질껀데 그러면 나중에 운영에서 문제가 될거같아요

2023-02-21 12:22 UTC, kihwankim approved these changes
good 고생하셨습니다!

2023-02-21 12:39 UTC, merged