item, category repository, service 구현 및 테스트코드 작성
SLCube/shop pull request #4
Opened 2023-01-15 09:30 UTC by SLCube

기존에 Item, Category Entity를 ManyToMany로 설정하여 중간에 ManyToMany를 풀어내는 ItemCategory Entity가 존재했으나 설계가 잘못된것같아 삭제 처리했습니다.

테스트코드 작성을 수월하게 위해 Spring Security의 의존성을 제거했습니다.

현재 Service Layer에서 매개변수 및 반환 타입을 Dto타입을 이용했는데 Controller Layer와 Service Layer 둘중 어느곳에서 사용하는것이 좋은지 궁금합니다.

또한 Service Layer에서 매개변수와 반환 타입을 Dto타입을 사용해 테스트코드에서 setter 메소드를 사용했는데 setter메소드를 대체할 방법이 무엇이 있을지 궁금합니다.

그 외로 구현을 하면서 여러가지 방법을 사용해서 통일이 안된 부분이 보이는데 예를들어 어느 dto에선 Builder패턴을 사용하고 어느 dto에선 생성자의 매개변수를 Entity를 받아 생성한다던지 각 방법들의 장단점을 같이 얘기해보고 싶어 여러 방법을 사용했습니다.

그 외로 눈에 보이는 안좋은 습관이라던가 설계상의 결함이 있으면 지적해주심 감사하겠습니다.

2023-01-15 16:30 UTC, kihwankim requested changes
전반적으로 리팩토링 해야할 부분과 코드 상에서 이슈가 나중에 발생할 부분들 지적을 했어요
category 설계 부분이랑 one to many에서 많은 row가 예상되는 것은 미리 제거하는걸 추천드려서 리뷰를 남겼어요! 확인 후 수정 바랍니다

2023-01-15 16:30 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/category/domain/Category.java
> +    }
category 이름을 변경하는 dto class가 여러개가 되면 dto class 별로 updateCategory method가 중복이 됩니다.
```suggestion
    public void updateCategory(String newCategoryName) {
        this.categoryName = newCategoryName;
    }
```

위와 같이 변경하는건 얼떨까요??

2023-01-15 16:30 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/category/dto/CategorySaveRequestDto.java
> +    }
많은 기업에서 toEntity() method를 dto class에 넣는걸 안티 패턴으로 보고 있어요
예를들어 category class 에 컬럼이 추가될 경우 모든 dto class 하나 하나 다 찾아야 하는 이슈가 발행하기 때문이죠
static factory method를 mapper class 에 따로 생성하는게 어떨까요??

같은 기능을 한곳에 모으는게 응집력 측면에서 좋아 보여서요

2023-01-15 16:30 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/category/domain/Category.java
> +
요렇게 category 순환 참조는 jpa에서 문한 loop발생 이슈를 초래할 수 있어요 저는 이방식을 추천하지 않고
category 하위에 하위 category를 넣고싶으면
category_binding 이라는 table을 추 가해서
level, parent, child 등을 담아서 처리하는게 좋아보여요

2023-01-15 16:30 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/category/service/CategoryServiceImpl.java
> +        return new CategoryResponseDto(category);
해당 코드를 Helper class로 따로 빼면어떨까요??
```suggestion
        Category category = categoryRepsitoryHelper(categoryRepository, categoryId);
        return new CategoryResponseDto(category);
```
중복되는 코드가 많아지면 요렇게 처리하면 중복 코드가 많이 줄어들듯합니다.

2023-01-15 16:30 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/category/service/CategoryServiceImpl.java
> +    public List<CategoryListResponseDto> findCategories() {
method이름이 명시적이지 않아서 findAllCategories 라 좀더 좋아 보여요!

2023-01-15 16:30 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/item/domain/Item.java
> +
review는 적으면 0개 많으면 몇백만개가 될 수 있어요 이럴 경우 lazy fetch 로 가져오게 되면 heap 이 터지는 이슈가 발생할 수 있습니다. 이럴 경우 private 변수로 가지는게 더 안좋을 수 있어요

2023-01-15 16:30 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/item/repository/ItemQueryRepositoryImpl.java
> +                        category.id.eq(categoryId),
```suggestion
        return query.selectFrom(item)
                .innerJoin(item.category, category).joinFetch()
                .where(
                        category.id.eq(categoryId),
```
위와 같이 어떤 조인인지 명시해주고, `category` 정보를 주로 많이 사용할 거같은데 fetch join하는게 network 자원 및 성능 개선에 좋아 보이네요

2023-01-15 16:30 UTC, kihwankim commented on src/main/java/com/slcube/shop/common/domain/config/jpa/BooleanToYnConverter.java
> +    }
"Y", "N" 은 static final 변수로 빼는걸 추천드립니다! 어떤 의미를 담는지 해석을 해야지 알 수 있지만, static final 변수로 빼면 변수명으로 yes or no 라는 것을 알 수 있기 때문입니다.
그리고 더 추천 드리는것은 enum type으로 생성하는걸 추천드려요

2023-01-15 16:30 UTC, kihwankim commented on src/test/java/com/slcube/shop/business/category/service/CategoryServiceTest.java
> +        // given
```suggestion
    void saveCategoryTest() {
        // given
```
주로 컨벤션으로 인해서 method 뒤에 `Test` 붙입니다!

2023-01-15 16:30 UTC, kihwankim commented on src/test/java/com/slcube/shop/business/category/service/CategoryServiceTest.java
> +class CategoryServiceTest {
@SpringBootTest 내부에 `SpringExtension`이 있어서 굳이 안 써도 됩니다!

2023-01-16 11:49 UTC, SLCube commented on src/main/java/com/slcube/shop/business/category/domain/Category.java
> +
지금은 계층형 카테고리를 의도하지 않았습니다. 현재는 카테고리 하나에 여러 상품이 속해있을 수 있게끔 구조를 설계했습니다. 
그래서 category와 item의 관계를 oneToMany로 구성했습니다. 추후에 계층형 카테고리로 요구사항 변경 시나리오를 생각중인데 시나리오를 적용할때 참고 하겠습니다.

2023-01-16 12:14 UTC, SLCube commented on src/main/java/com/slcube/shop/business/item/domain/Item.java
> +
Eager fetch를 이용했을때 N + 1 문제가 생기는건 알고있습니다. lazy fetch로 갖고오게 됐을때 heap이 터지는 이슈에 대해선 잘 이해가 되지 않네요. 조금 더 구체적인 상황이 있을까요?

2023-01-16 12:37 UTC, kihwankim requested changes
one to many many to one을 붙이는게 편리할 수 있고 안 편리할 수 있는데, 현재 heap 이 터질 수 있는 코드가 많습니다. 해당 부분은 필수적으로 고쳐야할거같아요

2023-01-16 12:37 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/category/domain/Category.java
> +
item 이 해당 카테고리에 1000만개 이상 포함될 경우가 있을 수 있는데 이경우 heap 이 터질 수 있습니다

2023-01-16 12:37 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/item/domain/Item.java
> +
1개의 Item내부에 review가 1000만개이면 memory 가 버틸 수  없어 보여요
JPA N + 1이슈는 아닙니다.
만약 10개의 item 을 pagination으로 조회하고 review도 같이 조회하면 10 + (10 * 1000만개) row가 조회되는데 이 경우 memory가 버틸 수 없어 보입니다.

2023-01-16 13:00 UTC, SLCube commented
제가 이해한게 맞다면 OneToMany관계에서 Many측의 데이터가 과다하게 많을때 heap이 터질수 있는 이슈가 있어 OneToMany연관관계를 제거했습니다.

2023-01-17 00:15 UTC, kihwankim commented
네 위에 남겨주신게 맞아요!

2023-01-17 00:16 UTC, kihwankim approved these changes
고생했습니다!

2023-01-17 00:16 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/item/repository/ItemQueryRepositoryImpl.java
> +                        category.id.eq(categoryId),
왜 이부분은 수정 안되어있는데 reseolve를 했는지 알 수 있을까요??

2023-01-17 00:21 UTC, merged