구현이 완료되지 않았지만 궁금한점이 있어 리뷰요청 합니다.
SLCube/shop pull request #5
Opened 2023-01-17 11:48 UTC by SLCube

1. 현재 **RepositoryHelper Class의 내용이 중복되는데 이러한 중복을 없애고 싶습니다.

2. MemberService는 추후에 개발 예정인데 Review에는 Member의 정보가 필요할때 어떻게 테스트를 진행하는지 궁금합니다.

2023-01-18 01:15 UTC, kihwankim requested changes
어디서 중복되는지 찍어주세요 이렇게 리뷰 요청하면 저가 하나씩 다 찾아야해서 힘들거같네요

Issue도 등록 해서 해주세요

2023-01-19 00:00 UTC, kihwankim requested changes
1. 번사항은 리뷰에 남겨져 있어요 확인 해주시면될거같아요!
2. memory 부터 구현해야 할거같아요 그래야지 다음에 코드 수정 비율을 줄일 수있을꺼같아서요
3. 생성 시점이 동일하면 같은 package에 두는게 좋아서 그렇게 진행해주시면되요

2023-01-19 00:00 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/review/repository/ReviewRepositoryHelper.java
> +    }
만약 generic 을 넣게 된다면 Repository Class Type 1개 Exception type1개 return type 1개로 generic 만 3개가 들어가게되요 그러면 중복 코드 처리 보다 generic 넣는게 더 힘들어지게 될거같아서 다음과 같이 요청을 드렸어요
generic 을 넣는게 더 좋다고 생각들면 해보시고 힘들면 다시 rollback하셔도되요

그리고 helper class 가 동일하면 error message도 외부 주입을 해줘야하니.... 중복이 findById 외에 하나도 없어 보이네요

2023-01-19 00:00 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/review/service/ReviewServiceImpl.java
> +
Service를 interface 로 분리하신 이유가 따로있나요??
interface가 너무 많을 경우 가독성 이슈가 생겨서 간단한거인경우 interface가 아닌 구체 클래스를 사용해도 됩니다

2023-01-19 00:00 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/review/service/ReviewServiceImpl.java
> +        Item item = itemRepositoryHelper.findByNotDeleted(itemRepository, itemId);
필드 변수가 너무 많아지고 있네요 나중에 mocking할때 힘들 수 있을거같아요
```suggestion
    private final ReviewRepository reviewRepository;
    private final ReviewRepositoryHelper reviewRepositoryHelper;
    private final ReviewValidation reviewValidation;
    private final ReportedReviewRepository reportedReviewRepository;

    @Override
    public Long saveReview(ReviewSaveRequestDto requestDto) {
        Long itemId = requestDto.getItemId();
        Item item = reviewValidation.validateCreateReview(itemId);
```

요렇게 하는게 어떨까요?
그러면 필드변수 2개를 줄일 수 있을거같아요

2023-01-19 00:00 UTC, kihwankim approved these changes

2023-01-19 00:00 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/review/service/ReviewServiceImpl.java
> +        Item item = itemRepositoryHelper.findByNotDeleted(itemRepository, itemId);
validation은 편하게 바꾸실껀지 아니면 안바꾸실껀지 결정해서 반영 해주세요~!

2023-01-19 11:34 UTC, SLCube commented on src/main/java/com/slcube/shop/business/review/repository/ReviewRepositoryHelper.java
> +    }
추후에 generic을 넣는걸 시도해보겠습니다. 의견 감사합니다

2023-01-19 11:36 UTC, SLCube commented on src/main/java/com/slcube/shop/business/review/service/ReviewServiceImpl.java
> +
이부분에 대해선 저도 고민이 있었습니다. 간단한 경우엔 특히 interface와 구현체가 1:1인 경우에도 인터페이스가 꼭 필요할까 항상 고민하는 내용인데 설계단계에서 interface를 생성해 그대로 진행하고 있었습니다. 가독성 이슈가 생기게된다면 정리하도록 하겠습니다.

2023-01-19 11:53 UTC, SLCube commented
2번 질문에 답변에 대한 이야기인데 memory라면 member entity에 대한 간단한 memory저장소를 말씀하시는건가요?

2023-01-20 05:14 UTC, kihwankim requested changes
2번에 대한 답은 member 를 개발을 먼저해야한다는 뜻이예요!

2023-01-20 05:14 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/review/service/ReviewServiceImpl.java
> +
여기 주석을 하는 이유가 없어 보이는데 지워주세요!

2023-01-20 05:14 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/repository/MemberMemoryRepository.java
> +    }
이걸 쓰는이유가 어떤건가요??

2023-01-20 06:44 UTC, SLCube commented on src/main/java/com/slcube/shop/business/member/repository/MemberMemoryRepository.java
> +    }
처음 질문 2번에 답변을 memory라고 답변하셔서 member에 대한 memory 저장소를 간단히 구현하라는 의미로 이해했습니다. 제거 후 member entity에 대한 기능부터 구현하겠습니다.

2023-01-20 07:07 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/review/service/ReviewServiceImpl.java
> +
일단 유지하고 나중에 불필요하면 없애죠

2023-01-20 07:08 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/review/repository/ReviewRepositoryHelper.java
> +    }
네네

2023-01-20 07:08 UTC, kihwankim approved these changes
고생하셨습니다

2023-01-20 10:35 UTC, merged