feat: member service 간단히 구현
SLCube/shop pull request #7
Opened 2023-01-20 11:36 UTC by SLCube

spring security를 적용시키지 않은 상태에서 member에대한 기능을 간단히 구현했습니다.

2023-01-21 09:19 UTC, kihwankim requested changes
현재 custom exception 처리가 필요해 보이는 로직이 많네요 커스텀 exception 생성과 exception handler 추가를 요청드려요

추가로 password는 무조건 암호화 하는게 좋습니다! 암호화 알고리즘 lib를 gradle에1 implementation 하고 작업해주세요!

2023-01-21 09:19 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
>      private LocalDateTime signUpDate;
이건 그냥 base time entity 해서 createTime 으로 대체하면될거같아요!

2023-01-21 09:19 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
>      private boolean isSignOut;
boolean type 보다는 enum type으로 처리하는게 더 깔끔할거같아요

2023-01-21 09:19 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/repository/MemberRepository.java
> +    public Optional<Member> login(@Param("email") String email, @Param("password") String password);
login 은 너무 쿼리문과 직관적이지 않은데 혹시 find by email 로 대체 하는게 좋을거같아요 그리고 password는 암호화 없이 넣는건 위험하므로 bcript 알고리즘을 넣어주는걸 추천드립니다

비즈니스 로직에서 password를 비교하는게 적절해 보이네요

2023-01-21 09:19 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/service/MemberServiceImpl.java
> +
Helper class 로 리팩토링이 필요해 보입니다
그리고 슬슬 custom exception으로 not found를처리하는 방식을 고려하는게 좋을거 같아요

2023-01-21 09:19 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/service/MemberServiceImpl.java
> +                .orElseThrow(() -> new IllegalArgumentException("회원 정보를 찾을 수 없습니다."));
password는 service에서 비교하도록 변경이 필요해 보이네요

2023-01-21 09:19 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/service/MemberServiceImpl.java
> +    // 테스트의 편의를 위해 실제 코드에 메소드를 추가하는게 맞는걸까 다른 방법은 없을까
이주석은 코드와 관련없어 보이네요 이런 주석은 review 요청때 넣어준면 좋을거같아요

2023-01-21 10:15 UTC, SLCube commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
>      private boolean isSignOut;
삭제여부는 단순히 true, false로 나타낼수있지만 계정의 상태는 두가지 상태가 아닌 다른 상태도 가질수 있기 때문인가요?

2023-01-21 12:16 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
>      private boolean isSignOut;
그냥 계정 status 라고하는게 좋을거 같아요
계정탈퇴 계정 삭제 계정 정지 등 여러 상태값이 될수있지만 boolean은 2개밖에 안되니 확장성이 떨어지죠

2023-01-21 12:24 UTC, SLCube commented on src/main/java/com/slcube/shop/business/member/domain/Member.java
>      private boolean isSignOut;
네 알겠습니다.

2023-01-21 12:48 UTC, SLCube commented
Custom Exception을 처음부터 구현해본건 처음인거같네요 부족한점 지적해주시면 감사하겠습니다.

2023-01-24 06:20 UTC, kihwankim requested changes
default excepton handler추가 부탁드려요
추가로 exception type을 여러개 설정 부탁드려요 그래야지 http response code 값을 설정할 수 있으니까요

마지막으로 이 pr을 merge한 이후에 jacoco 설정을 하면좋을거같네요
jacoco 설정 관련 issue등록 부탁드립니다

2023-01-24 06:20 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/item/repository/ItemRepositoryHelper.java
> +                .orElseThrow(() -> new CustomException(ITEMS_NOT_FOUND));
CustomException 을 상속받는 ItemNotFoundException을 새로 만들어서 하는게 어떨까요?? 너무 가독성이 안좋아보여서요

2023-01-24 06:20 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/domain/MemberStatus.java
> +}
```suggestion
public enum MemberStatus {
    MEMBER, EXCLUDED
}
```

와 같이 회원인지 아닌 회원탈퇴인지로 바꾸는게 어떨까요?? 왜냐하면 나중에 admin 케이스 ...etc 를 설정할경우 이름 정하기 애매 해질거같아서요

2023-01-24 06:20 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/repository/MemberRepository.java
> +    public Optional<Member> findByEmail(@Param("email") String email);
위 query와 같이 사용하게 되면 enum type을 사용하는 이유가 사라지기 때문에 파라미터로 enum type을 넣는게 어떨까요??

2023-01-24 06:20 UTC, kihwankim commented on src/main/java/com/slcube/shop/common/exception/CustomErrorResponse.java
> +                        .error(errorCode.getHttpStatus().name())
enum type을 반환하면 자동으로 name이 호출되어서 그냥 enum type을 넣어주면 될거같아요!

2023-01-24 06:20 UTC, kihwankim commented on src/main/java/com/slcube/shop/common/exception/CustomExceptionHandler.java
> +    }
이부분은 진짜 good!!
추가로 밑에 Exception.class 에 대한 Handler추가 부탁드려요!

2023-01-24 06:20 UTC, kihwankim commented on src/main/java/com/slcube/shop/common/domain/BaseEntity.java
>      private String createdBy;
여기 createdBy를 설정할때 어떤 값을 입력하는지 알 수 있을까요??

2023-01-24 10:46 UTC, SLCube commented on src/main/java/com/slcube/shop/business/item/repository/ItemRepositoryHelper.java
> +                .orElseThrow(() -> new CustomException(ITEMS_NOT_FOUND));
예외 상황마다 CustomException을 상속받는 Exception을 만들게 되면 Exception Class가 많아질거같은데 이런경우엔 어떻게 처리하면 깔끔할까요?

2023-01-24 11:24 UTC, SLCube commented on src/main/java/com/slcube/shop/business/member/repository/MemberRepository.java
> +    public Optional<Member> findByEmail(@Param("email") String email);
제가 의도했던건 사용가능한 계정인지를 따져서 member의 정보를 갖고 오려는것 이었는데, 
query를 "select m from Member m where m.email = :email and m.memberStatus <> 'EXCLUDED'" 이렇게쓰는건 어떻게 생각하시나요?

2023-01-24 11:26 UTC, SLCube commented on src/main/java/com/slcube/shop/common/domain/BaseEntity.java
>      private String createdBy;
등록한사람의 이름이 입력됩니다.

2023-01-24 11:42 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/item/repository/ItemRepositoryHelper.java
> +                .orElseThrow(() -> new CustomException(ITEMS_NOT_FOUND));
그냥 많이 많들어도 되요 적다고 좋은것도 아니고 exception handler 더 세분화 해서 처리하는 경우도 많아서요

2023-01-24 11:43 UTC, kihwankim commented on src/main/java/com/slcube/shop/business/member/repository/MemberRepository.java
> +    public Optional<Member> findByEmail(@Param("email") String email);
not equal 문 `<>`를 쓰는건 성능 문제가 발생하므로 left outer join으로 성능 개선을 해야 합니다.
eume type을 파라미터로 받아서 처리 하면되죠!

2023-01-24 11:51 UTC, kihwankim requested changes
logging추가 요청드려요 그리고, 질문에 대한 답을 적었는데 납득이 될 경우 resolve를하고 수정해주시면됩니다. 만약 납득이 안될 경우 우선 하고싶은방식으로 처리하고, 나중에 힘들면 변경하는 형태로 진행할게요
저가 답글을 남긴건 전부 직접 resolve눌러 주시면됩니다!

2023-01-24 11:51 UTC, kihwankim commented on src/main/java/com/slcube/shop/common/exception/CustomExceptionHandler.java
> +    }
```suggestion
    @ExceptionHandler(Exception.class)
    protected ResponseEntity handleException(Exception e) {
        log.error("interval server error", e);
        return CustomErrorResponse.toResponseEntity(CustomErrorCode.INTERNAL_SERVER_ERROR);
    }
```


default exception인경우 logging 넣어주세요! log.error(~~) 로 해주면 나중에 의도치 않은장애가 나면 이거 보고 처리가 가능하기 때문입니다.

2023-01-24 12:48 UTC, kihwankim approved these changes
good 고생 많으셨네요

2023-01-24 13:03 UTC, merged